apiVersion: v1
kind: ServiceAccount
metadata:
  name: bug-triage-sa
  namespace: bug-triage
  annotations:
    # Allows pods using this SA to inherit AWS IAM permissions to read S3 buckets
    eks.amazonaws.com/role-arn: arn:aws:iam::014498631376:role/bug-triage-s3-read-role